server:
    port: 7082


mybatis-plus:
    type-aliases-package: com.pokio.ideabook.entity
    mapper-locations: classpath:/mapper/*Mapper.xml

spring:
    datasource:
        url: jdbc:mysql://
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver


